services:
  traefik:
    logging:
      driver: "local" # Do some log rotation by default
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "letsencrypt_data:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

  gatewayd:
    logging:
      driver: "local" # Do some log rotation by default
    image: fedimint/gatewayd:master
    command: gatewayd ldk
    environment:
      # Path to folder containing gateway config and data files
      - FM_GATEWAY_DATA_DIR=/gateway_data
      # Gateway webserver listen address
      - FM_GATEWAY_LISTEN_ADDR=0.0.0.0:80
      # Public URL from which the webserver API is reachable
      - FM_GATEWAY_API_ADDR=${FM_GATEWAY_DOMAIN}/api/
      # Gateway webserver authentication password
      - FM_GATEWAY_PASSWORD=${FM_GATEWAY_PASSWORD}
      # Configured gateway routing fees Format: <base_msat>,<proportional_millionths>
      - FM_GATEWAY_FEES=0,${FM_GATEWAY_FEES_PROPORTIONAL}
      # LDK esplora server url
      - FM_LDK_ESPLORA_URL=${FM_LDK_ESPLORA_URL}
      # LDK network
      - FM_LDK_NETWORK=${FM_LDK_NETWORK}
      # LDK port
      - FM_PORT_LDK=${FM_PORT_LDK}
    volumes:
      - gateway_datadir:/gateway_data
    restart: always
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gatewayd.loadbalancer.server.port=80"
      - "traefik.http.routers.gatewayd.rule=Host(`${FM_GATEWAY_DOMAIN} && Path(`/api/`)`)"
      - "traefik.http.routers.gatewayd.entrypoints=websecure"
      - "traefik.http.routers.gatewayd.tls.certresolver=myresolver"

  gateway-ui:
    logging:
      driver: "local" # Do some log rotation by default
    image: fedimintui/fedimint-ui:0.4.3
    # image: gateway-ui
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - PORT=3001
      - REACT_APP_FM_GATEWAY_API=${FM_GATEWAY_DOMAIN}/api/
      - REACT_APP_FM_GATEWAY_PASSWORD=${FM_GATEWAY_PASSWORD}
    depends_on:
      - gatewayd
    restart: always
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gateway-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.gateway-ui.rule=Host(`${FM_GATEWAY_DOMAIN}`)"
      - "traefik.http.routers.gateway-ui.entrypoints=websecure"
      - "traefik.http.routers.gateway-ui.tls.certresolver=myresolver"

volumes:
  letsencrypt_data:
  gateway_datadir:
